### PR TITLE
Enlarge m_buttonStates array to prevent crash

### PR DESCRIPTION
**Pull request by aclex**
Enlarge m_buttonStates array member to next "maximum" value to prevent segfault in case of connecting joystick with more, than 11 buttons (reproducible e.g. with Sony DualShock 3).

Generally, if it's possible, maybe some dynamic container would be even safer here.

### CODE REVIEW

**Comment by billbonney** [comment]
probably better to check here for adding greater than array size
https://github.com/aclex/apm_planner/blob/c0a305a456720a189e2d8c055337374bef6ec349/src/ui/JoystickWidget.cc#L79

**Comment by aclex** [comment]
@billbonney yes, but it would lead to exclusion of several additional buttons, which otherwise could be fully working — there's even no interface artifacts in the form.

**Comment by billbonney** [comment]
@aclex I mean that as an addition to increasing the size array to avoid a segfault in the future for my under 96keyed joystick ;-)

**Comment by aclex** [comment]
@billbonney ahh, ok :-) surely

**Comment by aclex** [comment]
@billbonney maybe, indeed should I make it more safe with QVector-ish auto-enlarged array? Just wanted keep changes as little, as possible, but generally I think, I could fix it to have no hard limit.

**Comment by billbonney** [comment]
Thanks. Apologies for not getting this merged into the main code until now.

**Comment by aclex** [comment]
No problem) Thanks for merging it!

**Pull request merged**
