### PR TITLE
Flightplan: Introduced GraphicsItem base class for graphics items on map

### PR DESCRIPTION
**Pull request by hdino**
Follow-up pull request to PR #1083 .

The commit introduces a new GraphicsItem base class for 1st-level child graphics items shown on the map (currently: GPSItem, HomeItem, UAVItem, WaypointItem). This approach allows an easy extension of the items and avoids duplicated code.

I struggled a bit with [mapgraphicitem.cpp:125](https://github.com/ArduPilot/apm_planner/pull/1085/files#diff-4ca69cb6bc9197e2f5d3734df23ca9acL125): Does it make sense to emit the mapChanged() signal after each item having updated its position or would it be sufficient to emit this signal once after all positions are updated?

### CODE REVIEW

**Comment by Arne-W** [comment]
Regarding the mapChanged() signal I would be very careful - if you move it out of the loop test carefully. We had several issues regarding waypoint lines and icons. See #1019, #1024

**Comment by Arne-W** [comment]
@hdino Nice to see you - you will have to rebase your PR in order to build against the new C++11 enabled project!

**Comment by hdino** [comment]
Ah, thanks. Let's see what Travis thinks about it... :)

**Comment by Arne-W** [comment]
Seems like Travis did it 🎉 I will merge it this weekend. Thanks you for the contribution 👍

**Pull request merged**
