### PR TITLE
Replaced all isinf() and isnan()

### PR DESCRIPTION
**Pull request by Arne-W**
I replaced all isinf() and isnan() by qIsInf() and qIsNaN() and made a clean build on ubuntu 16.04 with Qt 5.4.2, 5.5.1 and 5.6.2. All builds were OK and a quick startup works as normal.
This should fix the build issues with Qt 5.6.X referenced in #959

### CODE REVIEW

**Comment by billbonney** [comment]
This is one way to fix it. these functions are defined in c++11 which I have on in OSX build. I can pull in these changes, but I'd like to know a bit more why.

Also building with Qt5.6.2 triggers linux-g++ build and Qt5.5.1

qt5.5.1
```
10:51:06: Starting: "/usr/lib/x86_64-linux-gnu/qt5/bin/qmake" /home/bonney/dev_src/apm_planner/apm_planner.pro -r -spec linux-g++-64 CONFIG+=debug
Project MESSAGE: Qt version 5.5.1
Project MESSAGE: Linux build x64_86
```

Qt5.6.2
```
/home/bonney/dev_src/apm_planner/apm_planner.pro -r -spec linux-g++ CONFIG+=debug
Project MESSAGE: Qt version 5.6.2
Project MESSAGE: Linux build x86
```

**Comment by Arne-W** [comment]
As far as I know the isnan() used by our code is C99 since C++11 there is a std::isnan(). The qIsNaN() is defined in Qtglobal.h
by the way - on my ubuntu all builds are default x86 builds. I have to change the -spec always by hand.

**Comment by billbonney** [comment]
OK. If travis passes I'll merge this in as is. But i might look at some Linux build cleanup.

Even though the build is linux-g++ its a 64bit build. Which is interesting...

```
bonney@bonney-1604-VirtualBox:~$ qmake -query 
QT_SYSROOT:
QT_INSTALL_PREFIX:/usr
QT_INSTALL_ARCHDATA:/usr/lib/x86_64-linux-gnu/qt5
QT_INSTALL_DATA:/usr/share/qt5
QT_INSTALL_DOCS:/usr/share/qt5/doc
QT_INSTALL_HEADERS:/usr/include/x86_64-linux-gnu/qt5
QT_INSTALL_LIBS:/usr/lib/x86_64-linux-gnu
QT_INSTALL_LIBEXECS:/usr/lib/x86_64-linux-gnu/qt5/libexec
QT_INSTALL_BINS:/usr/lib/x86_64-linux-gnu/qt5/bin
QT_INSTALL_TESTS:/usr/tests
QT_INSTALL_PLUGINS:/usr/lib/x86_64-linux-gnu/qt5/plugins
QT_INSTALL_IMPORTS:/usr/lib/x86_64-linux-gnu/qt5/imports
QT_INSTALL_QML:/usr/lib/x86_64-linux-gnu/qt5/qml
QT_INSTALL_TRANSLATIONS:/usr/share/qt5/translations
QT_INSTALL_CONFIGURATION:/etc/xdg
QT_INSTALL_EXAMPLES:/usr/lib/x86_64-linux-gnu/qt5/examples
QT_INSTALL_DEMOS:/usr/lib/x86_64-linux-gnu/qt5/examples
QT_HOST_PREFIX:/usr
QT_HOST_DATA:/usr/lib/x86_64-linux-gnu/qt5
QT_HOST_BINS:/usr/lib/x86_64-linux-gnu/qt5/bin
QT_HOST_LIBS:/usr/lib/x86_64-linux-gnu
QMAKE_SPEC:linux-g++-64
QMAKE_XSPEC:linux-g++-64
QMAKE_VERSION:3.0
QT_VERSION:5.5.1

bonney@bonney-1604-VirtualBox:~$ ~/Qt5.6.2/5.6/gcc_64/bin/qmake -query 
QT_SYSROOT:
QT_INSTALL_PREFIX:/home/bonney/Qt5.6.2/5.6/gcc_64
QT_INSTALL_ARCHDATA:/home/bonney/Qt5.6.2/5.6/gcc_64
QT_INSTALL_DATA:/home/bonney/Qt5.6.2/5.6/gcc_64
QT_INSTALL_DOCS:/home/bonney/Qt5.6.2/Docs/Qt-5.6
QT_INSTALL_HEADERS:/home/bonney/Qt5.6.2/5.6/gcc_64/include
QT_INSTALL_LIBS:/home/bonney/Qt5.6.2/5.6/gcc_64/lib
QT_INSTALL_LIBEXECS:/home/bonney/Qt5.6.2/5.6/gcc_64/libexec
QT_INSTALL_BINS:/home/bonney/Qt5.6.2/5.6/gcc_64/bin
QT_INSTALL_TESTS:/home/bonney/Qt5.6.2/5.6/gcc_64/tests
QT_INSTALL_PLUGINS:/home/bonney/Qt5.6.2/5.6/gcc_64/plugins
QT_INSTALL_IMPORTS:/home/bonney/Qt5.6.2/5.6/gcc_64/imports
QT_INSTALL_QML:/home/bonney/Qt5.6.2/5.6/gcc_64/qml
QT_INSTALL_TRANSLATIONS:/home/bonney/Qt5.6.2/5.6/gcc_64/translations
QT_INSTALL_CONFIGURATION:/home/bonney/Qt5.6.2/5.6/gcc_64
QT_INSTALL_EXAMPLES:/home/bonney/Qt5.6.2/Examples/Qt-5.6
QT_INSTALL_DEMOS:/home/bonney/Qt5.6.2/Examples/Qt-5.6
QT_HOST_PREFIX:/home/bonney/Qt5.6.2/5.6/gcc_64
QT_HOST_DATA:/home/bonney/Qt5.6.2/5.6/gcc_64
QT_HOST_BINS:/home/bonney/Qt5.6.2/5.6/gcc_64/bin
QT_HOST_LIBS:/home/bonney/Qt5.6.2/5.6/gcc_64/lib
QMAKE_SPEC:linux-g++
QMAKE_XSPEC:linux-g++
QMAKE_VERSION:3.0
QT_VERSION:5.6.2
```

**Comment by Arne-W** [comment]
My system behaves exactly the same - all properties match.

**Pull request merged**
