### PR TITLE
Main Window: Consistent style of main toolbar

### PR DESCRIPTION
**Pull request by sutherlandm**
The main window toolbar would follow the style of host OS (bright blue with Windows 7, or two tone gray on Ubuntu for example). Will now always have black background (to match the APM toolbar) and white text with either indoor or outdoor style/color. 'Inner' menus still follow the dark/light style.

### CODE REVIEW

**Comment by billbonney** [comment]
Looks a bit odd with the menu drop down not being in sync with the color 
This change has no impact on OSX
menucolor

**Comment by sutherlandm** [comment]
I was on the fence about how it looked, changed it so it will always look like below. Not sure why OSX would not work, I'll look into it.  
colour_fix

**Comment by sutherlandm** [comment]
Ah right. Ok well it is up to you if you want to change it or close this to just leave things as is for now, my feelings won't be hurt. Would it be worth exploring the option of no menu bar like Mission Planner?

**Comment by billbonney** [comment]
Closed: For now we are keeping it as is. Thanks for the proposal though 👍

**Pull request closed without merging**
