### PR TITLE
build: Update to 2.0.26-rc1

### PR DESCRIPTION
**Pull request by billbonney**
- Updated for 2.0.26-rc1 for beta testing
- Updates Travis to use Qt 5.9.3 
    - macOS 10.12 Xcode 9.2
    - linux

### CODE REVIEW

**Comment by Arne-W** [comment]
@billbonney What has to be done now? Who builds the rc versions and deploys them to the ardupilot firmware page?

**Comment by billbonney** [comment]
@Arne-W I've updated my build server to use Qt5.9.3 and it auto uploads the mac build when complete. I'll merge into beta for the rc release tomorrow. 

Others will sometimes publish windows/linux variants.

**Comment by Arne-W** [comment]
@billbonney I just thought it would be good if the releases @dcarpy builds could be stored on the firmware page too. He builds releases for several different plattorms and always shares them via dropbox - wouldn't it be better to have the workimng ones together at one place?

**Comment by dcarpy** [comment]
@billbonney @Arne-W 
Hi Bill.  Please pickup rc1 from here (Windows and Linux):
https://www.dropbox.com/sh/pqd66ncnqw7km2b/AAAyCbYSaqanXIhckVNOeIzra?dl=0

Thanks in advance!

**Pull request merged**
