### PR TITLE
Update SDL2 and command line to compile

### PR DESCRIPTION
**Pull request by Iragne**
I did some update on the SDL2 framework and also the command line. 
the issue appear after a full update on mac

### CODE REVIEW

**Comment by Iragne** [comment]
QT version 5.15.10
MacOSX13.1.sdk

**Comment by Arne-W** [comment]
Nice - thank you. 
Could you please change the git message to something like:
``Build: Update SDL2 and command line to compile. Fixes #1289 #1290``

The ``Fixes`` forces the issues to be closed when merging this PR which makes it easier to maintain the issues and to see the relations between issues and their Fixes. 
The ``Build:`` should show the part of the planner which is changed by the commit. You can find a full list [here](https://docs.google.com/spreadsheets/d/1pvwlyny6EMIYt-viCxiLug-BUYC-jSYIWxciZIntUew/edit?pli=1#gid=0). There is also a link in the [CONTRIBUTING.md](https://github.com/ArduPilot/apm_planner/blob/master/CONTRIBUTING.md) file

**Review by Arne-W — APPROVED** [review]

**Comment by Iragne** [comment]
Ok sure I'm on it

**Comment by Iragne** [comment]
I will read it in detail sorry, i will be careful on my Next PR

**Comment by Arne-W** [comment]
No problem - thanks for your contribution!

**Review by Arne-W — APPROVED** [review]

**Pull request merged**
