### PR TITLE
uas: update to the latest mavlink messages

### PR DESCRIPTION
**Pull request by muramura**
I am seeing "UNABLE TO DECODE MESSAGE NUMBER XXX" in the MESSAGES tag.
I have a new MAVLINK.

### CODE REVIEW

**Comment by Arne-W** [comment]
@muramura As I don't have a system do verify your change at the moment :disappointed: I have two questions: Did you test your change and are you sure it will work?

**Comment by Arne-W** [comment]
@muramura can you please add the Mavlink commit ID to allow others to which version is used excatly.
Somthing like `Mavlink: update to commit 6e08c075 from https://github.com/ArduPilot/mavlink` would be very nice.

**Comment by muramura** [comment]
I am confirming the operation with this PR.
Below are the messages before and after the change.

AFTER
Screenshot from 2022-05-20 08-14-26

BEFORE
Screenshot from 2022-05-20 08-19-49

**Comment by Arne-W** [comment]
@muramura your change added about 2500 warnings due to unaligned pointer access. Please provide better quality next time.

**Comment by muramura** [comment]
In my PR'd branch, there are 12 WARNING.

Screenshot from 2022-05-30 08-50-57

**Comment by Arne-W** [comment]
@muramura take a look at [this file line 31 to 43](https://github.com/ArduPilot/apm_planner/pull/1255/files#diff-c4b287d51a5bff269f27d4be43f8de2ae0bb0e396499c5306e77d34bb38fa71e). You removed the suppression for the warnings generated by gcc newer than 8.x.x. If you are using a gcc older than this you wont see the warnings. Nevertheless the suppression was well documented so there was no reason to remove it.

**Pull request merged**
