### PR TITLE
Added Statkart_Basemap - (with Svalbard topo) - and cleaned up formatting a bit.

### PR DESCRIPTION
**Pull request by AndKe**

### CODE REVIEW

**Comment by AndKe** [comment]
@Arne-W  - please accept til PR and build an .Appimage  - I will need it at Svalbard in 10 days. :) Thank you

**Comment by AndKe** [comment]
@Arne-W - I do not know if it's a lot of work for you to make this appimage - I might try to compile it on Ubuntu 20.04 myself if you are busy.   please tell if you will be able to build this version. - or maybe tell me how to build appimage on 20.04 (is that build-environment somehow accessible to me?)

**Comment by Arne-W** [comment]
@AndKe I will build an Appimage for you this evening - I didn't forget you only very busy in the last days...

**Comment by AndKe** [comment]
@Arne-W  Thank you. In the meantime - I discovered that I could cache the needed maps on my build, then use it with the appimage(that works with missions).
I understand that your time is precious, and you may postpone it if you like, I am set for now. :)

**Review by Arne-W — APPROVED** [review]

**Comment by Arne-W** [comment]
@AndKe I made an Appimage for you and put it in my dropbox. [This is the link](https://www.dropbox.com/s/ftjyh12namhnv62/APM-Planner_2-2.0.30-rc2-DEV-x86_64.AppImage?dl=0)
It is a dev build, and I will remove the download in the next days. It is build from the current master.
Have Fun!

**Pull request merged**
